export const inventoryItems = [
  {
    item_id: 'e4d8a9cf-1234-5678-9101',
    name: 'Dell XPS 15',
    category: 'Device',
    serial_number: 'DELL12345',
    condition: 'New',
    status: 'Borrowed',
    created_at: new Date(),
  },
  {
    item_id: 'f5e6d7c8-1234-5678-9101',
    name: 'Office Chair',
    category: 'Furniture',
    serial_number: 'CHAIR12345',
    condition: 'Worn Out',
    status: 'Available',
    created_at: new Date(),
  },
  {
    item_id: 'a1b2c3d4-5678-9101-1234',
    name: 'Blender',
    category: 'Food Utensil',
    serial_number: 'BLEND12345',
    condition: 'New',
    status: 'Borrowed',
    created_at: new Date(),
  },
  {
    item_id: 'b2c3d4e5-6789-1011-1234',
    name: 'Vacuum Cleaner',
    category: 'Cleaning Material',
    serial_number: 'VAC12345',
    condition: 'Broken',
    status: 'Available',
    created_at: new Date(),
  },
  {
    item_id: 'c3d4e5f6-7891-0111-1234',
    name: 'Desk',
    category: 'Furniture',
    serial_number: 'DESK12345',
    condition: 'New',
    status: 'Borrowed',
    created_at: new Date(),
  },
  {
    item_id: 'd4e5f6g7-8910-1112-1234',
    name: 'Microwave',
    category: 'Food Utensil',
    serial_number: 'MICRO12345',
    condition: 'Worn Out',
    status: 'Available',
    created_at: new Date(),
  },
];
